version: '2'
services:
  sandbox:
    build: .
    image: timmyraynor/zeppelin-docker:latest
    hostname: sandbox
    ports:
     - "8088:8088"
     - "50070:50070"
     - "4040:4040"
     - "8042:8042"
     - "8090:8090"
    command: -d
  minio:
    image: "minio/minio"
    hostname: minio
    ports: 
     - "9000:9000"
    environment:
        - MINIO_ACCESS_KEY=hello
        - MINIO_SECRET_KEY=helloworld
    command: server /exports